### ISSUE TITLE
warmup: true isn't working in the serverless.yml file

### ISSUE THREAD

**Issue by shaunajisc** [JiscSD/octopus#128]
We need to investigate why `warmup: true` isn't working in the serverless.yml file. We think serverless handles this and it's something we'll need to take a look at in the future

**Comment by AshleyRedmanJisc** [comment]
Doing some digging here, from what I can see, the serverless warmup plugin now needs to define a 'warmer' under the 'custom' key of the yml file. Then each function specifies a 'warmer' to use, so rather than the current where 'warmup' is set to true, we are getting the error ```unrecognized property 'warmup'``` because the key warmup is not referencing anything. 

The example given on the plugin[ github](https://github.com/juanjoDiaz/serverless-plugin-warmup) looks like this:

There is also a closed issue raised, which the [maintainer has mentioned](https://github.com/juanjoDiaz/serverless-plugin-warmup/issues/222) that the serverless framework has changed so the change of plugin is needed i guess. 

```
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      folderName: '.warmup' # Name of the folder created for the generated warmup 
      cleanFolder: false
      memorySize: 256
      name: warmer-default
      role: WarmupRole
      tags:
        Project: foo
        Owner: bar 
      vpc: false
      events:
        - schedule: 'cron(0/5 8-17 ? * MON-FRI *)' # Run WarmUp every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
      package:
        individually: true
        patterns:
          - '!../**'
          - '!../../**'
          - ./**
      timeout: 20
      tracing: true
      verbose: false # Disable the logs
      logRetentionInDays: 10
      prewarm: true # Run WarmUp immediately after a deploymentlambda
      clientContext:
        source: my-custom-source
        other: '20'
      payload: 
        source: my-custom-source
        other: 20
      payloadRaw: true # Won't JSON.stringify() the payload, may be necessary for Go/AppSync deployments
      concurrency: 5 # Warm up 5 concurrent instances
    
functions:
  myColdfunction:
    handler: 'myColdfunction.handler'
    events:
      - http:
          path: my-cold-function
          method: post
    warmup:
      default:
        enabled: false
```
